
#---standard pioneer footprint---
#---(in meters)---

footprint: [[-0.31, -0.31], [-0.31, 0.281], [0.2831, 0.2831], [0.31, -0.31]]
footprint_padding: 0.02

transform_tolerance: 0.2
map_type: costmap

always_send_full_costmap: true

obstacle_layer:
 enabled: true
 obstacle_range: 3.0
 raytrace_range: 4.0
 inflation_radius: 0.5
 track_unknown_space: true
 combination_method: 1
 max_obstacle_height: 0.6  #??????????????????????
 min_obstacle_height: 0.15
 observation_sources: PointCloud
 PointCloud: {sensor_frame: velodyne, data_type: PointCloud2, topic: /aligned_points, marking: true, clearing: true}


inflation_layer:
  enabled:              true
  cost_scaling_factor:  10  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.5  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic:            "/map"
