local_costmap:
  footprint: [[-0.3, -0.26], [-0.3, 0.26], [0.3, 0.26], [0.3, -0.26]]
  footprint_padding: 0.02
  global_frame: 3dmap
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.05
  transform_tolerance: 1
  inflation_radius: 0.3
  plugins:
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}

  obstacle_layer:
    observation_sources: velodyne
    velodyne: {
      data_type: PointCloud2,
      topic: /velodyne_points,
      marking: true,
      clearing: true,
      min_obstacle_height: 0.2,
      max_obstacle_height: 2.5
    }

